### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by brendanw36** [vinceliuice/Graphite-kde-theme#1]
The link to the GTK version of this theme in the README is correct, but the text says "Canta gtk theme".  The line in the README should be changed from
`[Canta gtk theme](https://github.com/vinceliuice/Graphite-gtk-theme)`
to
`[Graphite gtk theme](https://github.com/vinceliuice/Graphite-gtk-theme)`

**Comment by NotteShock** [comment]
@brendanw36 you can close this issue, it's resolved
