### ISSUE TITLE
How to remove inner rims?

### ISSUE THREAD

**Issue by ShabirK21** [vinceliuice/Graphite-kde-theme#13]
How can remove the white frames around this? Im using kvantum with the theme

![2023-01-08T13_58_46,673873912+08_00](https://user-images.githubusercontent.com/67749458/211182769-49110555-9016-4a8e-a0cb-fe8c1d517ff0.png)

**Comment by vinceliuice** [comment]
Download the last version on github master then run: `./install.sh --rimless`

**Comment by ShabirK21** [comment]
Thanks that worked.
