### ISSUE TITLE
Rim disappears when panel is floating

### ISSUE THREAD

**Issue by NextPr0gram** [vinceliuice/Graphite-kde-theme#18]
![Screenshot_20230813_150114](https://github.com/vinceliuice/Graphite-kde-theme/assets/80346666/91b700e2-c5ea-408f-9dd2-8e17b467399c)
![Screenshot_20230813_150139](https://github.com/vinceliuice/Graphite-kde-theme/assets/80346666/a48ebb6b-f348-45e4-949e-2aadac06df6d)

**Comment by vinceliuice** [comment]
Do not support the float panel
