### ISSUE TITLE
Bottom bar

### ISSUE THREAD

**Issue by SkelyTony** [vinceliuice/Graphite-kde-theme#6]
Hi, thank you for creating this beautiful theme, I just wanted to ask if there is a way to get rid of this empty border at the bottom.
![image](https://user-images.githubusercontent.com/78977752/154803314-81d32750-7ed2-42aa-a71e-00b753bc4344.png)

**Comment by vinceliuice** [comment]
Change the aurorae theme to no rounded one

**Comment by SkelyTony** [comment]
There seems to be only this theme, which i use. And both the dark and white variant seem to have the same border problem
![image](https://user-images.githubusercontent.com/78977752/154805272-add0272f-cd36-43d8-a7ca-55b59289221a.png)
![image](https://user-images.githubusercontent.com/78977752/154805310-3ad40541-ad60-47f4-ba75-c61c635f3bf0.png)

**Comment by vinceliuice** [comment]
Install from github, maybe there is something wrong about this on setting

**Comment by SkelyTony** [comment]
I did it. Thank you. Can you add the non rounded borders to the plasma "get new window decorations" store. I think many people prefer installing themes that way. Once again thank you for all of your themes, they are works of art!

**Comment by vinceliuice** [comment]
No problem! I'll update this
