### ISSUE TITLE
Are there gonna be Tweaks?

### ISSUE THREAD

**Issue by 0yen4snafu** [vinceliuice/Graphite-kde-theme#7]
Installing the GTK theme offers tweaks, which I really fancy, especially with `--tweaks rimless black normal`

Would anything like that be possible? Or could you make a black version at the very least? 
(Trying out Kvantum but nothing that matches the GTK theme with tweaks)

Thank you.

**Comment by dainbrump** [comment]
+1 for a rimless Window Decorations option. I tried setting "Window border size" to no borders and it only partly removes the border and only with the Graphite-dark theme, not the Graphite-dark-round theme.
